defaults:
  - _self_
  - type@_here_: development
paths:
  datasets:
    root: datasets
    raw: ${.root}/raw
    processed: ${.root}/processed
    final: ${.root}/final
    database: ${.root}/database
debug: true
