defaults:
  - _self_
  - type@_here_: development
paths:
  datasests:
    root: datasets
    raw: ${.root}/raw
    processed: ${.root}/processed
    final: ${.root}/final
    database: ${.root}/database
  database:
    root: database/
debug: true
